In [1]:
import numpy as np

In [2]:
gamma=0.6
alpha=1

In [3]:
location_to_state = {'A':0,'B':1,'C':2,'D':3,'E':4,'F':5,'G':6,'H':7,'I':8,'J':9,'K':10,'L':11}
print(location_to_state)

{'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H': 7, 'I': 8, 'J': 9, 'K': 10, 'L': 11}


In [4]:
reward= np.array([
                    [0,0,0,1,0,0,0,0,0,0,0,0],
                    [0,1000,1,0,0,0,0,0,0,0,0,0],
                    [0,1,0,0,0,1,0,0,0,0,0,0],
                    [1,0,0,0,1,0,1,0,0,0,0,0],
                    [0,0,0,1,0,1,0,0,0,0,0,0],
                    [0,0,1,0,1,0,0,0,1,0,0,0],
                    [0,0,0,1,0,0,0,1,0,0,0,0],
                    [0,0,0,0,0,0,1,0,0,0,1,0],
                    [0,0,0,0,0,1,0,0,0,0,0,1],
                    [0,0,0,0,0,0,0,0,0,0,1,0],
                    [0,0,0,0,0,0,0,0,0,1,0,1],
                    [0,0,0,0,0,0,0,0,1,0,1,0]
                    ])

In [5]:
Q= np.array(np.zeros([12,12]))
print(Q)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [6]:
for x in range(1000):
    current_location=np.random.randint(0,12)
    next_actions= []
    for y in range(12):
        if reward[current_location, y]>0:
            next_actions.append(y)
    next_location=np.random.choice(next_actions)
    temp_difference= reward[current_location,next_location]+gamma*Q[next_location, np.argmax(Q[next_location,])]-Q[current_location,next_location]
    Q[current_location,next_location]=Q[current_location,next_location]+alpha*temp_difference
        

In [7]:
print(Q.astype(int))

[[   0    0    0  196    0    0    0    0    0    0    0    0]
 [   0 2499  901    0    0    0    0    0    0    0    0    0]
 [   0 1500    0    0    0  541    0    0    0    0    0    0]
 [ 119    0    0    0  326    0  119    0    0    0    0    0]
 [   0    0    0  196    0  541    0    0    0    0    0    0]
 [   0    0  901    0  326    0    0    0  326    0    0    0]
 [   0    0    0  196    0    0    0   72    0    0    0    0]
 [   0    0    0    0    0    0  119    0    0    0  119    0]
 [   0    0    0    0    0  541    0    0    0    0    0  196]
 [   0    0    0    0    0    0    0    0    0    0  119    0]
 [   0    0    0    0    0    0    0    0    0   72    0  196]
 [   0    0    0    0    0    0    0    0  326    0  119    0]]


In [8]:
state_to_location = {state: location for location, state in location_to_state.items()}


In [9]:
state_to_location

{0: 'A',
 1: 'B',
 2: 'C',
 3: 'D',
 4: 'E',
 5: 'F',
 6: 'G',
 7: 'H',
 8: 'I',
 9: 'J',
 10: 'K',
 11: 'L'}

In [10]:
def route(starting_location, ending_location):
    route = [starting_location]
    next_location = starting_location
    while (next_location != ending_location):
        starting_state = location_to_state[starting_location]
        next_state = np.argmax(Q[starting_state,])
        next_location = state_to_location[next_state]
        route.append(next_location)
        starting_location = next_location
    return route    


In [ ]:
print(route('A','K'))
print("hello")
